version: "3.7"

services:
  app:
    image: node
    user: "node"
    working_dir: /home/node/app
    volumes:
    - ./app:/home/node/app
    ports:
    - 8080:8080
    command: ["yarn", "run", "dev-server"]
    #command: ["node", "server/server.js"]
